Update AlphaAnimals_CE_Patch_Race_Black_Hive.xml
Juanfrank/CombatExtended pull request #3
Opened 2020-05-02 22:43 UTC by Breadbox2k19

Acc and combat power update.

2020-05-02 22:57 UTC, Juanfrank commented
Please remove the accuracy modifiers since they're being added in the Projectile file

2020-05-02 22:58 UTC, Juanfrank requested changes
This

2020-05-04 15:32 UTC, Breadbox2k19 commented
I would also add pawn shooting accuracy to the animals just in case.

2020-05-04 18:03 UTC, Juanfrank approved these changes

2020-05-04 18:04 UTC, merged